kapiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"webapi-deployment","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"webapi"}},"template":{"metadata":{"labels":{"app":"webapi"}},"spec":{"containers":[{"image":"docker.io/szamurajek/eventdlarapi:latest","name":"webapi","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"32Mi"}}}]}}}}
  creationTimestamp: "2019-09-22T02:36:00Z"
  generation: 1
  name: webapi-deployment
  namespace: default
  resourceVersion: "32540"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/webapi-deployment
  uid: be7bcde3-f09a-421a-8f51-e11834180d34
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapi
    spec:
      containers:
      - image: docker.io/szamurajek/eventdlarapi:latest
        imagePullPolicy: Always
        name: webapi
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-09-22T02:36:00Z"
    lastUpdateTime: "2019-09-22T02:36:03Z"
    message: ReplicaSet "webapi-deployment-5fd478cbd9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-09-22T04:43:09Z"
    lastUpdateTime: "2019-09-22T04:43:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
