apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventer-deployment
spec:
  selector:
    matchLabels:
      app: eventer
  template:
    metadata:
      labels:
        app: eventer
    spec:
      containers:
        - name: eventer
          image: docker.io/szamurajek/eventdlarapi:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eventer-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - port: 3112
      targetPort: 80